name: .NET Core CI

on:
  push:
    branches: [ master, develop, hotfix/**, feature/**, bugfix/** ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: | 
        ASPNETCORE_ENVIRONMENT='Production'
        dotnet build --configuration Release
    - name: Test with dotnet
      run: | 
        ASPNETCORE_ENVIRONMENT='Production'
        dotnet test --configuration Release
